profile = "freven.vanilla:blocktypes_v1"
kind = "worldproperty"
code = "rock"

[[variants]]
id = "granite"
display = "Granite"
fallback_tint_rgba = "8C8580FF"
rock_group = "igneous"

[[variants]]
id = "limestone"
display = "Limestone"
fallback_tint_rgba = "C8C2A8FF"
rock_group = "sedimentary"

[[variants]]
id = "stone"
display = "Stone"
fallback_tint_rgba = "808080FF"
rock_group = "generic"
