schema = 1

[[block_tags]]
key = "freven:glass"
blocks = ["freven.vanilla:glass"]


[[block_tags]]
key = "freven:soils"
blocks = ["freven.vanilla:coarse_dirt", "freven.vanilla:dirt", "freven.vanilla:grass"]


[[block_tags]]
key = "freven:terrain_solids"
blocks = ["freven.vanilla:coarse_dirt", "freven.vanilla:dirt", "freven.vanilla:grass"]


[[block_tags]]
key = "freven:transparent_blocks"
blocks = ["freven.vanilla:glass"]
