schema = 1
# generated_from_profile = "freven.vanilla:blocktypes_v1"
# generated output is canonical content graph, not authoring source

[[materials]]
key = "freven.vanilla:block/glass"
texture = "freven.vanilla:textures/glass"
fallback_debug_tint_rgba = 2161704908
render_layer = "transparent"


[[block_visuals]]
key = "freven.vanilla:visuals/block/glass"
target = "freven.vanilla:glass"
model = "freven.vanilla:models/block/cube_all"

[block_visuals.materials]
all = "freven.vanilla:block/glass"

[[block_shapes]]
target = "freven.vanilla:glass"

[block_shapes.occludes]
bottom = false
top = false
north = false
south = false
east = false
west = false

[block_shapes.side_solid]
bottom = true
top = true
north = true
south = true
east = true
west = true

[[block_shapes.collision_boxes]]
min = [0.0, 0.0, 0.0]
max = [1.0, 1.0, 1.0]

[[block_shapes.selection_boxes]]
min = [0.0, 0.0, 0.0]
max = [1.0, 1.0, 1.0]
