profile = "freven.vanilla:blocktypes_v1"
kind = "cube_block"
code = "coarse_dirt"
display = "Coarse Dirt"
shape = "freven.vanilla:shapes/block/cube"
texture = "freven.vanilla:textures/coarse_dirt"
fallback_debug_tint_rgba = 2052735231
tags = ["freven:terrain_solids", "freven:soils"]
