profile = "freven.vanilla:blocktypes_v1"
kind = "cube_block"
code = "dirt"
display = "Dirt"
shape = "freven.vanilla:shapes/block/cube"
texture = "freven.vanilla:textures/dirt"
fallback_debug_tint_rgba = 1800350463
tags = ["freven:terrain_solids", "freven:soils"]
