profile = "freven.vanilla:blocktypes_v1"
kind = "cube_block"
code = "glass"
display = "Glass"
shape = "freven.vanilla:shapes/block/cube"
texture = "freven.vanilla:textures/glass"
fallback_debug_tint_rgba = 2161704908
render_layer = "transparent"
tags = ["freven:transparent_blocks", "freven:glass"]
