profile = "freven.vanilla:blocktypes_v1"
kind = "face_block"
code = "grass"
display = "Grass Block"
shape = "freven.vanilla:shapes/block/cube_faces"
tags = ["freven:terrain_solids", "freven:soils"]

[[material_slots]]
slot = "bottom"
code = "grass_bottom"
texture = "freven.vanilla:textures/dirt"
fallback_debug_tint_rgba = 1800350463

[[material_slots]]
slot = "side"
code = "grass_side"
texture = "freven.vanilla:textures/coarse_dirt"
fallback_debug_tint_rgba = 2052735231

[[material_slots]]
slot = "top"
code = "grass_top"
texture = "freven.vanilla:textures/grass"
fallback_debug_tint_rgba = 1067666943
