profile = "freven.vanilla:blocktypes_v1"
kind = "topsoil_family"
code = "soil"
display = "Soil"
shape = "freven.vanilla:shapes/block/cube_faces"
fertility_group = "content/worldproperties/fertility.toml"
coverage_group = "content/worldproperties/grass_coverage.toml"
tags = ["freven:soils", "freven:terrain_solids"]

[templates.material]
key = "block/soil_{fertility}"
texture = "textures/soil_{fertility}"
fallback_debug_tint_rgba = "{fertility.fallback_tint_rgba}"
render_layer = "opaque"

[coverage.bare]
visual = "visuals/block/soil_{fertility}_bare"
shape = "freven.vanilla:shapes/block/cube"
material = "block/soil_{fertility}"

[coverage.sparse]
visual = "visuals/block/soil_{fertility}_sparse"
shape = "freven.vanilla:shapes/block/cube_faces"
bottom = "block/soil_{fertility}"
side = "block/soil_{fertility}_sparse_side"
top = "block/soil_{fertility}_sparse_top"

[coverage.normal]
visual = "visuals/block/soil_{fertility}_normal"
shape = "freven.vanilla:shapes/block/cube_faces"
bottom = "block/soil_{fertility}"
side = "block/soil_{fertility}_normal_side"
top = "block/soil_{fertility}_normal_top"
