schema = 1
id = "freven.vanilla"
version = "0.1.0"
title = "Vanilla"

[defaults]
worldgen = "freven.vanilla:flat"
character_controller = "freven.vanilla:humanoid"
client_control_provider = "freven.vanilla:humanoid_controls"

[content]
root = "content"
manifest = "content.manifest"

[requirements]
engine = ">=0.1.0"

[[mods]]
id = "freven.vanilla.core"
version = "^0.1"

[[mods]]
id = "freven.vanilla.essentials"
version = "^0.1"
