schema = 1

[[models]]
key = "freven.vanilla:models/block/cube_all"
kind = "cube_all"


[[models]]
key = "freven.vanilla:models/block/cube_faces"
kind = "cube_faces"


[[models]]
key = "freven.vanilla:models/block/topsoil_overlay"
kind = "cuboid_parts"
material_slots = ["base", "grass_side", "grass_top"]

[[models.parts]]
name = "base"
from = [0.0, 0.0, 0.0]
to = [1.0, 1.0, 1.0]

[models.parts.faces.bottom]
material = "base"

[models.parts.faces.east]
material = "base"

[models.parts.faces.north]
material = "base"

[models.parts.faces.south]
material = "base"

[models.parts.faces.top]
material = "base"

[models.parts.faces.west]
material = "base"

[[models.parts]]
name = "grass_overlay"
from = [0.0, 0.0, 0.0]
to = [1.0, 1.0, 1.0]

[models.parts.faces.east]
material = "grass_side"
cull = false
overlay = true

[models.parts.faces.north]
material = "grass_side"
cull = false
overlay = true

[models.parts.faces.south]
material = "grass_side"
cull = false
overlay = true

[models.parts.faces.top]
material = "grass_top"
cull = false
overlay = true

[models.parts.faces.west]
material = "grass_side"
cull = false
overlay = true
